name	'inkblot/bind'
version '2.0.3'
source	'git://github.com/inkblot/puppet-bind'
author	'inkblot'
license	'Apache 2.0'
summary 'BIND name server'
description 'A Puppet module to deploy and manage the ISC BIND server'
project_page 'https://github.com/inkblot/puppet-bind'

dependency 'puppetlabs/concat', '>= 1.0.0'
