name	'inkblot/bind'
version '1.0.0'
source	'git://github.com/inkblot/puppet-bind'
author	'inkblot'
license	'Apache 2.0'
summary 'BIND name server'
description 'A Puppet module to deploy and manage the ISC BIND server'
project_page 'https://github.com/inkblot/puppet-bind'

dependency 'ripienaar/concat', '>= 0.1.0'
